# Generated by Django 3.1 on 2020-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('shift', models.IntegerField()),
                ('image', models.ImageField(upload_to='face_data')),
            ],
        ),
    ]
