# Generated by Django 3.1 on 2020-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='face_data/'),
        ),
    ]
