# Generated by Django 3.1 on 2020-09-19 11:57

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(blank=True, max_length=200, null=True)),
                ('lecture', models.CharField(max_length=200, null=True)),
                ('rollnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True)),
                ('shift', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200, null=True)),
                ('lecture_number', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=attendance.models.user_dir_path)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('rollNumebr', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100, null=True)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, null=True)),
                ('shift', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=100, null=True)),
            ],
        ),
    ]
