# Generated by Django 3.1 on 2020-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='rollnumber',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
