# Generated by Django 3.1.4 on 2020-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201019_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
