# Generated by Django 3.1 on 2020-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_faculty_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
