# Generated by Django 3.1 on 2020-09-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_faculty_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
