# Generated by Django 3.1 on 2020-10-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20200927_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
        migrations.AddField(
            model_name='subject',
            name='sem1_subject_code',
            field=models.CharField(choices=[('310901', '310901'), ('310902', '310902'), ('310903', '310903'), ('310904', '310904'), ('310905', '310905'), ('310906', '310906')], default=310901, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subject_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.faculty')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=200, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('shift', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.faculty')),
            ],
        ),
    ]
