# Generated by Django 3.1 on 2020-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20201001_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sem1_subject_code',
            field=models.CharField(choices=[('310901', '310901'), ('310902', '310902'), ('310903', '310903'), ('310904', '310904'), ('310905', '310905'), ('310906', '310906'), ('310907', '310907'), ('310908', '310908')], max_length=200, primary_key=True, serialize=False),
        ),
    ]
