# Generated by Django 3.1 on 2020-10-02 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20201002_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='assigned_subjects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='null'),
            preserve_default=False,
        ),
    ]
