# Generated by Django 3.1 on 2020-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_faculty_assigned_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Lecture', 'Lecture'), ('Practical', 'Practical'), ('Guest', 'Guest')], max_length=200, null=True),
        ),
    ]
