# Generated by Django 3.1 on 2020-10-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20201003_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sem',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='assigned_shift',
        ),
    ]
