# Generated by Django 3.1 on 2020-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20201003_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
