# Generated by Django 3.1 on 2020-10-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20201003_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='faculty_id',
            new_name='faculty',
        ),
    ]
