# Generated by Django 3.1 on 2020-10-05 06:59

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20201004_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_number',
            field=models.IntegerField(default=attendance.models.Lecture.increment_lecture_number, primary_key=True, serialize=False),
        ),
    ]
