# Generated by Django 3.1 on 2020-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_auto_20201005_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
