# Generated by Django 3.1 on 2020-10-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_auto_20201006_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.TextField(blank=True, default=['None'], null=True),
        ),
    ]
