# Generated by Django 3.1 on 2020-10-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20201006_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tfrom',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tto',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
