# Generated by Django 3.1 on 2020-10-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_auto_20201009_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
