# Generated by Django 3.1 on 2020-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_auto_20201009_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollNumebr',
            new_name='rollNumber',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='assigned_subjects',
            field=models.TextField(blank=True, default=['None'], null=True),
        ),
    ]
